project_id: 621830
api_token_env: CROWDIN_PERSONAL_TOKEN_621830
base_path: "."
preserve_hierarchy: true
files:
  - source: /Configuration/Sets/*/labels.xlf
    translation: /%original_path%/%two_letters_code%.%original_file_name%
    languages_mapping:
      two_letters_code:
        fr-CA: fr_CA
        pt-BR: pt_BR
        zh-CN: zh_CN
        zh-HK: zh_HK
  - source: /Resources/Private/Language/locallang.xlf
    translation: /%original_path%/%two_letters_code%.%original_file_name%
    languages_mapping:
      two_letters_code:
        fr-CA: fr_CA
        pt-BR: pt_BR
        zh-CN: zh_CN
        zh-HK: zh_HK
  - source: /Resources/Private/Language/locallang_be.xlf
    translation: /%original_path%/%two_letters_code%.%original_file_name%
    languages_mapping:
      two_letters_code:
        fr-CA: fr_CA
        pt-BR: pt_BR
        zh-CN: zh_CN
        zh-HK: zh_HK
  - source: /Resources/Private/Language/locallang_db.xlf
    translation: /%original_path%/%two_letters_code%.%original_file_name%
    languages_mapping:
      two_letters_code:
        fr-CA: fr_CA
        pt-BR: pt_BR
        zh-CN: zh_CN
        zh-HK: zh_HK
