files:
  - source: /Resources/Private/Language/locallang*.xlf
    translation: /Resources/Private/Language/%two_letters_code%.%original_file_name%

  - source: /Configuration/Sets/KlaroConsentManager/labels.xlf
    translation: /Configuration/Sets/KlaroConsentManager/%two_letters_code%.%original_file_name%
