categories:
  klaroconsentmanager: ~
  klaroconsentmanager.templates:
    parent: klaroconsentmanager
  klaroconsentmanager.resources:
    parent: klaroconsentmanager
  klaroconsentmanager.settings:
    parent: klaroconsentmanager

settings:
  plugin.tx_klaroconsentmanager.view.templateRootPath:
    type: string
    default: 'EXT:klaro_consent_manager/Resources/Private/Templates/'
    category: klaroconsentmanager.templates
  plugin.tx_klaroconsentmanager.view.partialRootPath:
    type: string
    default: 'EXT:klaro_consent_manager/Resources/Private/Partials/'
    category: klaroconsentmanager.templates
  plugin.tx_klaroconsentmanager.view.layoutRootPath:
    type: string
    default: 'EXT:klaro_consent_manager/Resources/Private/Layouts/'
    category: klaroconsentmanager.templates
  plugin.tx_klaroconsentmanager.settings.css.klaro-default:
    type: string
    default: 'EXT:klaro_consent_manager/Resources/Public/Css/klaro.min.css'
    category: klaroconsentmanager.templates
  plugin.tx_klaroconsentmanager.settings.css.klaro-custom:
    type: string
    default: 'EXT:klaro_consent_manager/Resources/Public/Css/klaro-custom.min.css'
    category: klaroconsentmanager.resources
  plugin.tx_klaroconsentmanager.settings.javascript.klaro-default:
    type: string
    default: 'EXT:klaro_consent_manager/Resources/Public/JavaScript/klaro-no-translations-no-css.js'
    category: klaroconsentmanager.resources
  plugin.tx_klaroconsentmanager.settings.contextualconsent.replaceAttributes:
    type: string
    default: 'src,href'
    category: klaroconsentmanager.settings
  plugin.tx_klaroconsentmanager.settings.contextualconsent.mainSectionOnly:
    type: bool
    default: 1
    category: klaroconsentmanager.settings
  plugin.tx_klaroconsentmanager.settings.configuration.disabled:
    type: bool
    default: 0
    category: klaroconsentmanager.settings
